SCALE = 0.1

# Constants for screen size
SCREEN_WIDTH = 10400 * SCALE
SCREEN_HEIGHT = 7400 * SCALE

# Field size
FIELD_W = 9000 * SCALE
FIELD_H = 6000 * SCALE

WALL_THICKNESS = 0
LINE_THICKNESS = 1

# Constants for the goal
GOAL_WIDTH = 1000 * SCALE  # For Division B
GOAL_HEIGHT = 160 * SCALE
GOAL_DEPTH = 180 * SCALE
GOAL_WALL_THICKNESS = 20 * SCALE

# Goal positions
GOAL_Y_POSITION = SCREEN_HEIGHT / 2 - GOAL_WIDTH / 2
GOAL_1_X_POSITION = (SCREEN_WIDTH - FIELD_W) / 2 - GOAL_DEPTH
GOAL_2_X_POSITION = (SCREEN_WIDTH + FIELD_W) / 2
